server:
  port: 8000
spring:
  profiles:
    active: dev
  application:
    #项目名称必填，在注册中心唯一
    #最好和之前域名规范、kubernetes service名等保持一致（会作为调用）
    name: service-order
  cloud:
    nacos:
      discovery: #启用 spring cloud nacos discovery
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
          service-product:
            connectTimeout: 3000
            readTimeout: 5000

logging:
  level:
    com.study.service.order.feign: DEBUG

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
    activate:
      on-profile: dev

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
    activate:
      on-profile: uat

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
    activate:
      on-profile: prod