server:
  port: 9000
spring:
  profiles:
    active: dev
  application:
    #项目名称必填，在注册中心唯一
    #最好和之前域名规范、kubernetes service名等保持一致（会作为调用）
    name: service-product
  cloud:
    nacos:
      discovery: #启用 spring cloud nacos discovery
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}
---
spring:
  config:
    import:
      - nacos:common.properties?group=product
    activate:
      on-profile: dev

---
spring:
  config:
    import:
      - nacos:common.properties?group=product
    activate:
      on-profile: uat

---
spring:
  config:
    import:
      - nacos:common.properties?group=product
    activate:
      on-profile: prod


